import "./global.css";
import "./styles/globals.css";

import { Poppins } from "next/font/google";
import RootProvider from "@/components/providers/root-provider";

const poppis = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppis.className}>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
